/**
 * Données pays → devise, langues et format de date par défaut.
 * Utilisées dans les réglages : la devise et la langue se mettent à jour
 * automatiquement quand le pays est sélectionné.
 */

export interface CountryInfo {
  /** Nom français du pays. */
  name: string;
  /** Drapeau (emoji). */
  flag: string;
  /** Devises ISO 4217, la principale en premier. */
  currencies: string[];
  /** Langues officielles (noms français), la principale en premier. */
  languages: string[];
  /** Format de date le plus courant. */
  dateFormat: string;
}

export const COUNTRIES: CountryInfo[] = [
  { name: "Afghanistan", flag: "🇦🇫", currencies: ["AFN"], languages: ["Pachtou", "Dari"], dateFormat: "jj/mm/aaaa" },
  { name: "Afrique du Sud", flag: "🇿🇦", currencies: ["ZAR"], languages: ["Anglais", "Afrikaans", "Zoulou"], dateFormat: "jj/mm/aaaa" },
  { name: "Albanie", flag: "🇦🇱", currencies: ["ALL"], languages: ["Albanais"], dateFormat: "jj/mm/aaaa" },
  { name: "Algérie", flag: "🇩🇿", currencies: ["DZD"], languages: ["Arabe", "Tamazight"], dateFormat: "jj/mm/aaaa" },
  { name: "Allemagne", flag: "🇩🇪", currencies: ["EUR"], languages: ["Allemand"], dateFormat: "jj/mm/aaaa" },
  { name: "Andorre", flag: "🇦🇩", currencies: ["EUR"], languages: ["Catalan"], dateFormat: "jj/mm/aaaa" },
  { name: "Angola", flag: "🇦🇴", currencies: ["AOA"], languages: ["Portugais"], dateFormat: "jj/mm/aaaa" },
  { name: "Antigua-et-Barbuda", flag: "🇦🇬", currencies: ["XCD"], languages: ["Anglais"], dateFormat: "jj/mm/aaaa" },
  { name: "Arabie saoudite", flag: "🇸🇦", currencies: ["SAR"], languages: ["Arabe"], dateFormat: "jj/mm/aaaa" },
  { name: "Argentine", flag: "🇦🇷", currencies: ["ARS"], languages: ["Espagnol"], dateFormat: "jj/mm/aaaa" },
  { name: "Arménie", flag: "🇦🇲", currencies: ["AMD"], languages: ["Arménien"], dateFormat: "jj/mm/aaaa" },
  { name: "Australie", flag: "🇦🇺", currencies: ["AUD"], languages: ["Anglais"], dateFormat: "jj/mm/aaaa" },
  { name: "Autriche", flag: "🇦🇹", currencies: ["EUR"], languages: ["Allemand"], dateFormat: "jj/mm/aaaa" },
  { name: "Azerbaïdjan", flag: "🇦🇿", currencies: ["AZN"], languages: ["Azerbaïdjanais"], dateFormat: "jj/mm/aaaa" },
  { name: "Bahamas", flag: "🇧🇸", currencies: ["BSD"], languages: ["Anglais"], dateFormat: "jj/mm/aaaa" },
  { name: "Bahreïn", flag: "🇧🇭", currencies: ["BHD"], languages: ["Arabe"], dateFormat: "jj/mm/aaaa" },
  { name: "Bangladesh", flag: "🇧🇩", currencies: ["BDT"], languages: ["Bengali"], dateFormat: "jj/mm/aaaa" },
  { name: "Barbade", flag: "🇧🇧", currencies: ["BBD"], languages: ["Anglais"], dateFormat: "jj/mm/aaaa" },
  { name: "Belgique", flag: "🇧🇪", currencies: ["EUR"], languages: ["Néerlandais", "Français", "Allemand"], dateFormat: "jj/mm/aaaa" },
  { name: "Belize", flag: "🇧🇿", currencies: ["BZD"], languages: ["Anglais"], dateFormat: "jj/mm/aaaa" },
  { name: "Bénin", flag: "🇧🇯", currencies: ["XOF"], languages: ["Français"], dateFormat: "jj/mm/aaaa" },
  { name: "Bhoutan", flag: "🇧🇹", currencies: ["BTN"], languages: ["Dzongkha"], dateFormat: "jj/mm/aaaa" },
  { name: "Biélorussie", flag: "🇧🇾", currencies: ["BYN"], languages: ["Biélorusse", "Russe"], dateFormat: "jj/mm/aaaa" },
  { name: "Birmanie (Myanmar)", flag: "🇲🇲", currencies: ["MMK"], languages: ["Birman"], dateFormat: "jj/mm/aaaa" },
  { name: "Bolivie", flag: "🇧🇴", currencies: ["BOB"], languages: ["Espagnol", "Quechua", "Aimara"], dateFormat: "jj/mm/aaaa" },
  { name: "Bosnie-Herzégovine", flag: "🇧🇦", currencies: ["BAM"], languages: ["Bosniaque", "Croate", "Serbe"], dateFormat: "jj/mm/aaaa" },
  { name: "Botswana", flag: "🇧🇼", currencies: ["BWP"], languages: ["Anglais", "Tswana"], dateFormat: "jj/mm/aaaa" },
  { name: "Brésil", flag: "🇧🇷", currencies: ["BRL"], languages: ["Portugais"], dateFormat: "jj/mm/aaaa" },
  { name: "Brunei", flag: "🇧🇳", currencies: ["BND"], languages: ["Malais"], dateFormat: "jj/mm/aaaa" },
  { name: "Bulgarie", flag: "🇧🇬", currencies: ["BGN"], languages: ["Bulgare"], dateFormat: "jj/mm/aaaa" },
  { name: "Burkina Faso", flag: "🇧🇫", currencies: ["XOF"], languages: ["Français"], dateFormat: "jj/mm/aaaa" },
  { name: "Burundi", flag: "🇧🇮", currencies: ["BIF"], languages: ["Kirundi", "Français"], dateFormat: "jj/mm/aaaa" },
  { name: "Cambodge", flag: "🇰🇭", currencies: ["KHR"], languages: ["Khmer"], dateFormat: "jj/mm/aaaa" },
  { name: "Cameroun", flag: "🇨🇲", currencies: ["XAF"], languages: ["Français", "Anglais"], dateFormat: "jj/mm/aaaa" },
  { name: "Canada", flag: "🇨🇦", currencies: ["CAD"], languages: ["Anglais", "Français"], dateFormat: "jj/mm/aaaa" },
  { name: "Cap-Vert", flag: "🇨🇻", currencies: ["CVE"], languages: ["Portugais"], dateFormat: "jj/mm/aaaa" },
  { name: "Chili", flag: "🇨🇱", currencies: ["CLP"], languages: ["Espagnol"], dateFormat: "jj/mm/aaaa" },
  { name: "Chine", flag: "🇨🇳", currencies: ["CNY"], languages: ["Chinois"], dateFormat: "aaaa-mm-jj" },
  { name: "Chypre", flag: "🇨🇾", currencies: ["EUR"], languages: ["Grec", "Turc"], dateFormat: "jj/mm/aaaa" },
  { name: "Colombie", flag: "🇨🇴", currencies: ["COP"], languages: ["Espagnol"], dateFormat: "jj/mm/aaaa" },
  { name: "Comores", flag: "🇰🇲", currencies: ["KMF"], languages: ["Comorien", "Français", "Arabe"], dateFormat: "jj/mm/aaaa" },
  { name: "Congo (République démocratique)", flag: "🇨🇩", currencies: ["CDF"], languages: ["Français", "Lingala", "Swahili"], dateFormat: "jj/mm/aaaa" },
  { name: "Congo (République du)", flag: "🇨🇬", currencies: ["XAF"], languages: ["Français"], dateFormat: "jj/mm/aaaa" },
  { name: "Corée du Nord", flag: "🇰🇵", currencies: ["KPW"], languages: ["Coréen"], dateFormat: "aaaa-mm-jj" },
  { name: "Corée du Sud", flag: "🇰🇷", currencies: ["KRW"], languages: ["Coréen"], dateFormat: "aaaa-mm-jj" },
  { name: "Costa Rica", flag: "🇨🇷", currencies: ["CRC"], languages: ["Espagnol"], dateFormat: "jj/mm/aaaa" },
  { name: "Côte d'Ivoire", flag: "🇨🇮", currencies: ["XOF"], languages: ["Français"], dateFormat: "jj/mm/aaaa" },
  { name: "Croatie", flag: "🇭🇷", currencies: ["EUR"], languages: ["Croate"], dateFormat: "jj/mm/aaaa" },
  { name: "Cuba", flag: "🇨🇺", currencies: ["CUP"], languages: ["Espagnol"], dateFormat: "jj/mm/aaaa" },
  { name: "Danemark", flag: "🇩🇰", currencies: ["DKK"], languages: ["Danois"], dateFormat: "jj/mm/aaaa" },
  { name: "Djibouti", flag: "🇩🇯", currencies: ["DJF"], languages: ["Français", "Arabe"], dateFormat: "jj/mm/aaaa" },
  { name: "Dominique", flag: "🇩🇲", currencies: ["XCD"], languages: ["Anglais"], dateFormat: "jj/mm/aaaa" },
  { name: "Égypte", flag: "🇪🇬", currencies: ["EGP"], languages: ["Arabe"], dateFormat: "jj/mm/aaaa" },
  { name: "Émirats arabes unis", flag: "🇦🇪", currencies: ["AED"], languages: ["Arabe"], dateFormat: "jj/mm/aaaa" },
  { name: "Équateur", flag: "🇪🇨", currencies: ["USD"], languages: ["Espagnol"], dateFormat: "jj/mm/aaaa" },
  { name: "Érythrée", flag: "🇪🇷", currencies: ["ERN"], languages: ["Tigrigna", "Arabe"], dateFormat: "jj/mm/aaaa" },
  { name: "Espagne", flag: "🇪🇸", currencies: ["EUR"], languages: ["Espagnol"], dateFormat: "jj/mm/aaaa" },
  { name: "Estonie", flag: "🇪🇪", currencies: ["EUR"], languages: ["Estonien"], dateFormat: "jj/mm/aaaa" },
  { name: "Eswatini", flag: "🇸🇿", currencies: ["SZL"], languages: ["Swazi", "Anglais"], dateFormat: "jj/mm/aaaa" },
  { name: "États-Unis", flag: "🇺🇸", currencies: ["USD"], languages: ["Anglais"], dateFormat: "mm/jj/aaaa" },
  { name: "Éthiopie", flag: "🇪🇹", currencies: ["ETB"], languages: ["Amharique"], dateFormat: "jj/mm/aaaa" },
  { name: "Fidji", flag: "🇫🇯", currencies: ["FJD"], languages: ["Fidjien", "Anglais"], dateFormat: "jj/mm/aaaa" },
  { name: "Finlande", flag: "🇫🇮", currencies: ["EUR"], languages: ["Finnois", "Suédois"], dateFormat: "jj/mm/aaaa" },
  { name: "France", flag: "🇫🇷", currencies: ["EUR"], languages: ["Français"], dateFormat: "jj/mm/aaaa" },
  { name: "Gabon", flag: "🇬🇦", currencies: ["XAF"], languages: ["Français"], dateFormat: "jj/mm/aaaa" },
  { name: "Gambie", flag: "🇬🇲", currencies: ["GMD"], languages: ["Anglais"], dateFormat: "jj/mm/aaaa" },
  { name: "Géorgie", flag: "🇬🇪", currencies: ["GEL"], languages: ["Géorgien"], dateFormat: "jj/mm/aaaa" },
  { name: "Ghana", flag: "🇬🇭", currencies: ["GHS"], languages: ["Anglais"], dateFormat: "jj/mm/aaaa" },
  { name: "Grèce", flag: "🇬🇷", currencies: ["EUR"], languages: ["Grec"], dateFormat: "jj/mm/aaaa" },
  { name: "Grenade", flag: "🇬🇩", currencies: ["XCD"], languages: ["Anglais"], dateFormat: "jj/mm/aaaa" },
  { name: "Guatemala", flag: "🇬🇹", currencies: ["GTQ"], languages: ["Espagnol"], dateFormat: "jj/mm/aaaa" },
  { name: "Guinée", flag: "🇬🇳", currencies: ["GNF"], languages: ["Français"], dateFormat: "jj/mm/aaaa" },
  { name: "Guinée-Bissau", flag: "🇬🇼", currencies: ["XOF"], languages: ["Portugais"], dateFormat: "jj/mm/aaaa" },
  { name: "Guinée équatoriale", flag: "🇬🇶", currencies: ["XAF"], languages: ["Espagnol", "Français"], dateFormat: "jj/mm/aaaa" },
  { name: "Guyana", flag: "🇬🇾", currencies: ["GYD"], languages: ["Anglais"], dateFormat: "jj/mm/aaaa" },
  { name: "Haïti", flag: "🇭🇹", currencies: ["HTG"], languages: ["Créole haïtien", "Français"], dateFormat: "jj/mm/aaaa" },
  { name: "Honduras", flag: "🇭🇳", currencies: ["HNL"], languages: ["Espagnol"], dateFormat: "jj/mm/aaaa" },
  { name: "Hongrie", flag: "🇭🇺", currencies: ["HUF"], languages: ["Hongrois"], dateFormat: "jj/mm/aaaa" },
  { name: "Île Maurice", flag: "🇲🇺", currencies: ["MUR"], languages: ["Anglais", "Français"], dateFormat: "jj/mm/aaaa" },
  { name: "Islande", flag: "🇮🇸", currencies: ["ISK"], languages: ["Islandais"], dateFormat: "jj/mm/aaaa" },
  { name: "Inde", flag: "🇮🇳", currencies: ["INR"], languages: ["Hindi", "Anglais"], dateFormat: "jj/mm/aaaa" },
  { name: "Indonésie", flag: "🇮🇩", currencies: ["IDR"], languages: ["Indonésien"], dateFormat: "jj/mm/aaaa" },
  { name: "Irak", flag: "🇮🇶", currencies: ["IQD"], languages: ["Arabe", "Kurde"], dateFormat: "jj/mm/aaaa" },
  { name: "Iran", flag: "🇮🇷", currencies: ["IRR"], languages: ["Persan"], dateFormat: "jj/mm/aaaa" },
  { name: "Irlande", flag: "🇮🇪", currencies: ["EUR"], languages: ["Anglais", "Irlandais"], dateFormat: "jj/mm/aaaa" },
  { name: "Israël", flag: "🇮🇱", currencies: ["ILS"], languages: ["Hébreu", "Arabe"], dateFormat: "jj/mm/aaaa" },
  { name: "Italie", flag: "🇮🇹", currencies: ["EUR"], languages: ["Italien"], dateFormat: "jj/mm/aaaa" },
  { name: "Jamaïque", flag: "🇯🇲", currencies: ["JMD"], languages: ["Anglais"], dateFormat: "jj/mm/aaaa" },
  { name: "Japon", flag: "🇯🇵", currencies: ["JPY"], languages: ["Japonais"], dateFormat: "aaaa-mm-jj" },
  { name: "Jordanie", flag: "🇯🇴", currencies: ["JOD"], languages: ["Arabe"], dateFormat: "jj/mm/aaaa" },
  { name: "Kazakhstan", flag: "🇰🇿", currencies: ["KZT"], languages: ["Kazakh", "Russe"], dateFormat: "jj/mm/aaaa" },
  { name: "Kenya", flag: "🇰🇪", currencies: ["KES"], languages: ["Swahili", "Anglais"], dateFormat: "jj/mm/aaaa" },
  { name: "Kirghizistan", flag: "🇰🇬", currencies: ["KGS"], languages: ["Kirghize", "Russe"], dateFormat: "jj/mm/aaaa" },
  { name: "Kiribati", flag: "🇰🇮", currencies: ["AUD"], languages: ["Gilbertin", "Anglais"], dateFormat: "jj/mm/aaaa" },
  { name: "Koweït", flag: "🇰🇼", currencies: ["KWD"], languages: ["Arabe"], dateFormat: "jj/mm/aaaa" },
  { name: "Laos", flag: "🇱🇦", currencies: ["LAK"], languages: ["Laotien"], dateFormat: "jj/mm/aaaa" },
  { name: "Lesotho", flag: "🇱🇸", currencies: ["LSL"], languages: ["Sotho", "Anglais"], dateFormat: "jj/mm/aaaa" },
  { name: "Lettonie", flag: "🇱🇻", currencies: ["EUR"], languages: ["Letton"], dateFormat: "jj/mm/aaaa" },
  { name: "Liban", flag: "🇱🇧", currencies: ["LBP"], languages: ["Arabe"], dateFormat: "jj/mm/aaaa" },
  { name: "Libéria", flag: "🇱🇷", currencies: ["LRD"], languages: ["Anglais"], dateFormat: "jj/mm/aaaa" },
  { name: "Libye", flag: "🇱🇾", currencies: ["LYD"], languages: ["Arabe"], dateFormat: "jj/mm/aaaa" },
  { name: "Liechtenstein", flag: "🇱🇮", currencies: ["CHF"], languages: ["Allemand"], dateFormat: "jj/mm/aaaa" },
  { name: "Lituanie", flag: "🇱🇹", currencies: ["EUR"], languages: ["Lituanien"], dateFormat: "jj/mm/aaaa" },
  { name: "Luxembourg", flag: "🇱🇺", currencies: ["EUR"], languages: ["Luxembourgeois", "Français", "Allemand"], dateFormat: "jj/mm/aaaa" },
  { name: "Macédoine du Nord", flag: "🇲🇰", currencies: ["MKD"], languages: ["Macédonien"], dateFormat: "jj/mm/aaaa" },
  { name: "Madagascar", flag: "🇲🇬", currencies: ["MGA"], languages: ["Malgache", "Français"], dateFormat: "jj/mm/aaaa" },
  { name: "Malaisie", flag: "🇲🇾", currencies: ["MYR"], languages: ["Malais"], dateFormat: "jj/mm/aaaa" },
  { name: "Malawi", flag: "🇲🇼", currencies: ["MWK"], languages: ["Chichewa", "Anglais"], dateFormat: "jj/mm/aaaa" },
  { name: "Maldives", flag: "🇲🇻", currencies: ["MVR"], languages: ["Divehi"], dateFormat: "jj/mm/aaaa" },
  { name: "Mali", flag: "🇲🇱", currencies: ["XOF"], languages: ["Français", "Bambara"], dateFormat: "jj/mm/aaaa" },
  { name: "Malte", flag: "🇲🇹", currencies: ["EUR"], languages: ["Maltais", "Anglais"], dateFormat: "jj/mm/aaaa" },
  { name: "Maroc", flag: "🇲🇦", currencies: ["MAD"], languages: ["Arabe", "Amazighe"], dateFormat: "jj/mm/aaaa" },
  { name: "Marshall (Îles)", flag: "🇲🇭", currencies: ["USD"], languages: ["Marshallais", "Anglais"], dateFormat: "jj/mm/aaaa" },
  { name: "Mauritanie", flag: "🇲🇷", currencies: ["MRU"], languages: ["Arabe"], dateFormat: "jj/mm/aaaa" },
  { name: "Mexique", flag: "🇲🇽", currencies: ["MXN"], languages: ["Espagnol"], dateFormat: "jj/mm/aaaa" },
  { name: "Micronésie", flag: "🇫🇲", currencies: ["USD"], languages: ["Anglais"], dateFormat: "jj/mm/aaaa" },
  { name: "Moldavie", flag: "🇲🇩", currencies: ["MDL"], languages: ["Roumain"], dateFormat: "jj/mm/aaaa" },
  { name: "Monaco", flag: "🇲🇨", currencies: ["EUR"], languages: ["Français"], dateFormat: "jj/mm/aaaa" },
  { name: "Mongolie", flag: "🇲🇳", currencies: ["MNT"], languages: ["Mongol"], dateFormat: "jj/mm/aaaa" },
  { name: "Monténégro", flag: "🇲🇪", currencies: ["EUR"], languages: ["Monténégrin"], dateFormat: "jj/mm/aaaa" },
  { name: "Mozambique", flag: "🇲🇿", currencies: ["MZN"], languages: ["Portugais"], dateFormat: "jj/mm/aaaa" },
  { name: "Namibie", flag: "🇳🇦", currencies: ["NAD"], languages: ["Anglais"], dateFormat: "jj/mm/aaaa" },
  { name: "Nauru", flag: "🇳🇷", currencies: ["AUD"], languages: ["Nauruan", "Anglais"], dateFormat: "jj/mm/aaaa" },
  { name: "Népal", flag: "🇳🇵", currencies: ["NPR"], languages: ["Népalais"], dateFormat: "jj/mm/aaaa" },
  { name: "Nicaragua", flag: "🇳🇮", currencies: ["NIO"], languages: ["Espagnol"], dateFormat: "jj/mm/aaaa" },
  { name: "Niger", flag: "🇳🇪", currencies: ["XOF"], languages: ["Français"], dateFormat: "jj/mm/aaaa" },
  { name: "Nigeria", flag: "🇳🇬", currencies: ["NGN"], languages: ["Anglais"], dateFormat: "jj/mm/aaaa" },
  { name: "Norvège", flag: "🇳🇴", currencies: ["NOK"], languages: ["Norvégien"], dateFormat: "jj/mm/aaaa" },
  { name: "Nouvelle-Zélande", flag: "🇳🇿", currencies: ["NZD"], languages: ["Anglais", "Maori"], dateFormat: "jj/mm/aaaa" },
  { name: "Oman", flag: "🇴🇲", currencies: ["OMR"], languages: ["Arabe"], dateFormat: "jj/mm/aaaa" },
  { name: "Ouganda", flag: "🇺🇬", currencies: ["UGX"], languages: ["Anglais", "Swahili"], dateFormat: "jj/mm/aaaa" },
  { name: "Ouzbékistan", flag: "🇺🇿", currencies: ["UZS"], languages: ["Ouzbek"], dateFormat: "jj/mm/aaaa" },
  { name: "Pakistan", flag: "🇵🇰", currencies: ["PKR"], languages: ["Ourdou", "Anglais"], dateFormat: "jj/mm/aaaa" },
  { name: "Palaos", flag: "🇵🇼", currencies: ["USD"], languages: ["Palaosien", "Anglais"], dateFormat: "jj/mm/aaaa" },
  { name: "Panama", flag: "🇵🇦", currencies: ["PAB"], languages: ["Espagnol"], dateFormat: "jj/mm/aaaa" },
  { name: "Papouasie-Nouvelle-Guinée", flag: "🇵🇬", currencies: ["PGK"], languages: ["Anglais", "Tok pisin"], dateFormat: "jj/mm/aaaa" },
  { name: "Paraguay", flag: "🇵🇾", currencies: ["PYG"], languages: ["Espagnol", "Guarani"], dateFormat: "jj/mm/aaaa" },
  { name: "Pays-Bas", flag: "🇳🇱", currencies: ["EUR"], languages: ["Néerlandais"], dateFormat: "jj/mm/aaaa" },
  { name: "Pérou", flag: "🇵🇪", currencies: ["PEN"], languages: ["Espagnol", "Quechua"], dateFormat: "jj/mm/aaaa" },
  { name: "Philippines", flag: "🇵🇭", currencies: ["PHP"], languages: ["Filipino", "Anglais"], dateFormat: "mm/jj/aaaa" },
  { name: "Pologne", flag: "🇵🇱", currencies: ["PLN"], languages: ["Polonais"], dateFormat: "jj/mm/aaaa" },
  { name: "Portugal", flag: "🇵🇹", currencies: ["EUR"], languages: ["Portugais"], dateFormat: "jj/mm/aaaa" },
  { name: "Qatar", flag: "🇶🇦", currencies: ["QAR"], languages: ["Arabe"], dateFormat: "jj/mm/aaaa" },
  { name: "République centrafricaine", flag: "🇨🇫", currencies: ["XAF"], languages: ["Français", "Sango"], dateFormat: "jj/mm/aaaa" },
  { name: "République dominicaine", flag: "🇩🇴", currencies: ["DOP"], languages: ["Espagnol"], dateFormat: "jj/mm/aaaa" },
  { name: "République tchèque", flag: "🇨🇿", currencies: ["CZK"], languages: ["Tchèque"], dateFormat: "jj/mm/aaaa" },
  { name: "Roumanie", flag: "🇷🇴", currencies: ["RON"], languages: ["Roumain"], dateFormat: "jj/mm/aaaa" },
  { name: "Royaume-Uni", flag: "🇬🇧", currencies: ["GBP"], languages: ["Anglais"], dateFormat: "jj/mm/aaaa" },
  { name: "Russie", flag: "🇷🇺", currencies: ["RUB"], languages: ["Russe"], dateFormat: "jj/mm/aaaa" },
  { name: "Rwanda", flag: "🇷🇼", currencies: ["RWF"], languages: ["Kinyarwanda", "Français", "Anglais"], dateFormat: "jj/mm/aaaa" },
  { name: "Saint-Kitts-et-Nevis", flag: "🇰🇳", currencies: ["XCD"], languages: ["Anglais"], dateFormat: "jj/mm/aaaa" },
  { name: "Saint-Marin", flag: "🇸🇲", currencies: ["EUR"], languages: ["Italien"], dateFormat: "jj/mm/aaaa" },
  { name: "Saint-Vincent-et-les-Grenadines", flag: "🇻🇨", currencies: ["XCD"], languages: ["Anglais"], dateFormat: "jj/mm/aaaa" },
  { name: "Sainte-Lucie", flag: "🇱🇨", currencies: ["XCD"], languages: ["Anglais"], dateFormat: "jj/mm/aaaa" },
  { name: "Salomon (Îles)", flag: "🇸🇧", currencies: ["SBD"], languages: ["Anglais"], dateFormat: "jj/mm/aaaa" },
  { name: "Salvador", flag: "🇸🇻", currencies: ["USD"], languages: ["Espagnol"], dateFormat: "jj/mm/aaaa" },
  { name: "Samoa", flag: "🇼🇸", currencies: ["WST"], languages: ["Samoan", "Anglais"], dateFormat: "jj/mm/aaaa" },
  { name: "Sao Tomé-et-Principe", flag: "🇸🇹", currencies: ["STN"], languages: ["Portugais"], dateFormat: "jj/mm/aaaa" },
  { name: "Sénégal", flag: "🇸🇳", currencies: ["XOF"], languages: ["Français", "Wolof"], dateFormat: "jj/mm/aaaa" },
  { name: "Serbie", flag: "🇷🇸", currencies: ["RSD"], languages: ["Serbe"], dateFormat: "jj/mm/aaaa" },
  { name: "Seychelles", flag: "🇸🇨", currencies: ["SCR"], languages: ["Créole seychellois", "Français", "Anglais"], dateFormat: "jj/mm/aaaa" },
  { name: "Sierra Leone", flag: "🇸🇱", currencies: ["SLL"], languages: ["Anglais"], dateFormat: "jj/mm/aaaa" },
  { name: "Singapour", flag: "🇸🇬", currencies: ["SGD"], languages: ["Anglais", "Malais", "Chinois", "Tamoul"], dateFormat: "jj/mm/aaaa" },
  { name: "Slovaquie", flag: "🇸🇰", currencies: ["EUR"], languages: ["Slovaque"], dateFormat: "jj/mm/aaaa" },
  { name: "Slovénie", flag: "🇸🇮", currencies: ["EUR"], languages: ["Slovène"], dateFormat: "jj/mm/aaaa" },
  { name: "Somalie", flag: "🇸🇴", currencies: ["SOS"], languages: ["Somali", "Arabe"], dateFormat: "jj/mm/aaaa" },
  { name: "Soudan", flag: "🇸🇩", currencies: ["SDG"], languages: ["Arabe", "Anglais"], dateFormat: "jj/mm/aaaa" },
  { name: "Soudan du Sud", flag: "🇸🇸", currencies: ["SSP"], languages: ["Anglais"], dateFormat: "jj/mm/aaaa" },
  { name: "Sri Lanka", flag: "🇱🇰", currencies: ["LKR"], languages: ["Sinhala", "Tamoul"], dateFormat: "jj/mm/aaaa" },
  { name: "Suède", flag: "🇸🇪", currencies: ["SEK"], languages: ["Suédois"], dateFormat: "jj/mm/aaaa" },
  { name: "Suisse", flag: "🇨🇭", currencies: ["CHF"], languages: ["Allemand", "Français", "Italien"], dateFormat: "jj/mm/aaaa" },
  { name: "Suriname", flag: "🇸🇷", currencies: ["SRD"], languages: ["Néerlandais"], dateFormat: "jj/mm/aaaa" },
  { name: "Syrie", flag: "🇸🇾", currencies: ["SYP"], languages: ["Arabe"], dateFormat: "jj/mm/aaaa" },
  { name: "Tadjikistan", flag: "🇹🇯", currencies: ["TJS"], languages: ["Tadjik"], dateFormat: "jj/mm/aaaa" },
  { name: "Tanzanie", flag: "🇹🇿", currencies: ["TZS"], languages: ["Swahili", "Anglais"], dateFormat: "jj/mm/aaaa" },
  { name: "Tchad", flag: "🇹🇩", currencies: ["XAF"], languages: ["Français", "Arabe"], dateFormat: "jj/mm/aaaa" },
  { name: "Thaïlande", flag: "🇹🇭", currencies: ["THB"], languages: ["Thaï"], dateFormat: "jj/mm/aaaa" },
  { name: "Timor oriental", flag: "🇹🇱", currencies: ["USD"], languages: ["Tetum", "Portugais"], dateFormat: "jj/mm/aaaa" },
  { name: "Togo", flag: "🇹🇬", currencies: ["XOF"], languages: ["Français"], dateFormat: "jj/mm/aaaa" },
  { name: "Tonga", flag: "🇹🇴", currencies: ["TOP"], languages: ["Tongien", "Anglais"], dateFormat: "jj/mm/aaaa" },
  { name: "Trinité-et-Tobago", flag: "🇹🇹", currencies: ["TTD"], languages: ["Anglais"], dateFormat: "jj/mm/aaaa" },
  { name: "Tunisie", flag: "🇹🇳", currencies: ["TND"], languages: ["Arabe"], dateFormat: "jj/mm/aaaa" },
  { name: "Turkménistan", flag: "🇹🇲", currencies: ["TMT"], languages: ["Turkmène"], dateFormat: "jj/mm/aaaa" },
  { name: "Turquie", flag: "🇹🇷", currencies: ["TRY"], languages: ["Turc"], dateFormat: "jj/mm/aaaa" },
  { name: "Tuvalu", flag: "🇹🇻", currencies: ["AUD"], languages: ["Tuvaluan", "Anglais"], dateFormat: "jj/mm/aaaa" },
  { name: "Ukraine", flag: "🇺🇦", currencies: ["UAH"], languages: ["Ukrainien"], dateFormat: "jj/mm/aaaa" },
  { name: "Uruguay", flag: "🇺🇾", currencies: ["UYU"], languages: ["Espagnol"], dateFormat: "jj/mm/aaaa" },
  { name: "Vanuatu", flag: "🇻🇺", currencies: ["VUV"], languages: ["Bichelamar", "Français", "Anglais"], dateFormat: "jj/mm/aaaa" },
  { name: "Vatican", flag: "🇻🇦", currencies: ["EUR"], languages: ["Italien"], dateFormat: "jj/mm/aaaa" },
  { name: "Venezuela", flag: "🇻🇪", currencies: ["VES"], languages: ["Espagnol"], dateFormat: "jj/mm/aaaa" },
  { name: "Vietnam", flag: "🇻🇳", currencies: ["VND"], languages: ["Vietnamien"], dateFormat: "jj/mm/aaaa" },
  { name: "Yémen", flag: "🇾🇪", currencies: ["YER"], languages: ["Arabe"], dateFormat: "jj/mm/aaaa" },
  { name: "Zambie", flag: "🇿🇲", currencies: ["ZMW"], languages: ["Anglais"], dateFormat: "jj/mm/aaaa" },
  { name: "Zimbabwe", flag: "🇿🇼", currencies: ["ZWL"], languages: ["Anglais"], dateFormat: "jj/mm/aaaa" },
];

/** Toutes les devises présentes dans le jeu de données, triées. */
export const ALL_CURRENCIES: string[] = Array.from(
  new Set(COUNTRIES.flatMap((country) => country.currencies)),
).sort();

/** Toutes les langues présentes dans le jeu de données, triées. */
export const ALL_LANGUAGES: string[] = Array.from(
  new Set(COUNTRIES.flatMap((country) => country.languages)),
).sort();

/** Retrouve les infos d'un pays à partir de son nom français. */
export function findByCountry(name: string): CountryInfo | undefined {
  return COUNTRIES.find((country) => country.name === name);
}
